
DROP TABLE MEMBER;
DROP TABLE REALTOR;
DROP TABLE REALESTATE;
DROP TABLE SELLER;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE PRODUCT;
DROP TABLE PRODUCTIMG;


CREATE TABLE MEMBER (
MEMBER_NO      VARCHAR2(10) NOT NULL,
MEM_MOBILE     VARCHAR2(10),
MEM_ID             VARCHAR2(40) NOT NULL,
PASSWORD       VARCHAR2(40) NOT NULL,
MEM_NAME       VARCHAR2(12),
MEM_ADDR       VARCHAR2(100),
SEARCH_STATE   VARCHAR2(10),
LOCK_STATE     VARCHAR2(10),
MEM_GAME       NUMBER(10),
CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO) );

DROP SEQUENCE MEM_SEQ;
CREATE SEQUENCE MEM_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0988123456','SteveJobs','123456','賈伯斯','新北市萬里區一條路9號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0956222777','MichaelJordan','123456','喬丹','台北市內湖區灌籃路168號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0933987654','PeterWu','123456','彼得吳','台北市大安區中大路8號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0933987654','BillGates','123456','比爾蓋茲','桃園市中壢區中大路300號','ON','ON',0);


CREATE TABLE REALESTATE (
ESTATE_NO     VARCHAR2(10) NOT NULL,
ESTATE_NAME   VARCHAR2(40) NOT NULL,
CONSTRAINT ESTATE_PK PRIMARY KEY(ESTATE_NO) );

DROP SEQUENCE ESTATE_SEQ;
CREATE SEQUENCE ESTATE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'信義房屋');
INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'永慶房屋');
INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'東森房屋');


CREATE TABLE REALTOR (
REALTOR_NO      VARCHAR2(10) NOT NULL,
REALTOR_ID      VARCHAR2(40) NOT NULL,
PASSWORD        VARCHAR2(40) NOT NULL,
NAME            VARCHAR2(40),
PHOTO           BLOB,
AREA            VARCHAR2(40),
INTRODUCTION    CLOB,
ID_NO           VARCHAR2(10),
ESTATE_NO       VARCHAR2(10),
STATE           VARCHAR2(10),
CONSTRAINT REALTOR_ESTATE_FK FOREIGN KEY(ESTATE_NO) REFERENCES REALESTATE(ESTATE_NO),
CONSTRAINT REALTOR_PK PRIMARY KEY(REALTOR_NO) );

DROP SEQUENCE REALTOR_SEQ;
CREATE SEQUENCE REALTOR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR01@GMAIL.COM', '123456', '葦小寶', '北投區', 'A108064497', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR02@GMAIL.COM', '123456', '王建民', '中正區', 'B123456789', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR03@GMAIL.COM', '123456', '林志玲', '士林區', 'X298765432', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR04@GMAIL.COM', '123456', '張三豐', '內湖區', 'D165432178', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR05@GMAIL.COM', '123456', '林大偉', '大安區', 'C132165491', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR06@GMAIL.COM', '123456', '李進財', '信義區', 'A198765432', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR07@GMAIL.COM', '123456', '趙德助', '萬華區', 'H147258369', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR08@GMAIL.COM', '123456', '張鈞甯', '中山區', 'X265432155', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR09@GMAIL.COM', '123456', '王小明', '大同區', 'A123466593', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR10@GMAIL.COM', '123456', '陳金鋒', '大安區', 'F136925874', 'ESTATE0003', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR11@GMAIL.COM', '123456', '連天邊', '信義區', 'H118754326', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(REALTOR_NO, REALTOR_ID, PASSWORD, NAME, AREA, ID_NO, ESTATE_NO, STATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR12@GMAIL.COM', '123456', '楊美麗', '中正區', 'B213456789', 'ESTATE0001', 'ON');


CREATE TABLE SELLER (
SELLER_NO        VARCHAR2(10) NOT NULL,
COMPANY          VARCHAR2(40),
TAXID            VARCHAR2(10),
SELLER_ID        VARCHAR2(40) NOT NULL,
PASSWORD         VARCHAR2(40) NOT NULL,
CONTACT          VARCHAR2(40),
PHONE            VARCHAR2(10),
STATE            VARCHAR2(10),
INTRODUCTION     CLOB,
CONSTRAINT SELLER_PK PRIMARY KEY(SELLER_NO) );

DROP SEQUENCE SELLER_SEQ;
CREATE SEQUENCE SELLER_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO SELLER(SELLER_NO, COMPANY, TAXID, SELLER_ID, PASSWORD, CONTACT, PHONE, STATE)
VALUES('SL'||(LPAD(to_char(SELLER_SEQ.NEXTVAL),8,'0')), '宜家家居', '84309586', 'SALES@IKEA.COM', '123456', '李協達', '84128869', 'ON');
INSERT INTO SELLER(SELLER_NO, COMPANY, TAXID, SELLER_ID, PASSWORD, CONTACT, PHONE, STATE)
VALUES('SL'||(LPAD(to_char(SELLER_SEQ.NEXTVAL),8,'0')), '歐德傢俱', '70394175', 'SALES@ORDER.COM', '123456', '陳國都', '0800033988', 'ON');
INSERT INTO SELLER(SELLER_NO, COMPANY, TAXID, SELLER_ID, PASSWORD, CONTACT, PHONE, STATE)
VALUES('SL'||(LPAD(to_char(SELLER_SEQ.NEXTVAL),8,'0')), '特力屋', '89390488', 'SALES@HOLA.COM.TW', '123456', '何湯雄', '87915566', 'ON');
INSERT INTO SELLER(SELLER_NO, COMPANY, TAXID, SELLER_ID, PASSWORD, CONTACT, PHONE, STATE)
VALUES('SL'||(LPAD(to_char(SELLER_SEQ.NEXTVAL),8,'0')), '詩肯柚木', '89403884', 'SALES@HOLA.COM.TW', '123456', '林福勤', '03-3180555', 'ON');


CREATE TABLE PRODUCT_CATEGORY (
CATE_NO      VARCHAR2(10) NOT NULL,
CATE_NAME    VARCHAR2(100) NOT NULL,
CONSTRAINT PRDT_CATE_PK PRIMARY KEY(CATE_NO) );

CREATE SEQUENCE PRDT_CATE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO PRODUCT_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'桌子');
INSERT INTO PRODUCT_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'椅子');
INSERT INTO PRODUCT_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'櫃子');


CREATE TABLE PRODUCT (
PRODUCT_NO        VARCHAR2(10) NOT NULL,
SELLER_NO         VARCHAR2(10) NOT NULL,
CATEGORY_NO       VARCHAR2(10) NOT NULL,
PRODUCT_NAME      VARCHAR2(50) NOT NULL,
DESCRIPTION       CLOB,
STOCK             BLOB,
PRICE             NUMBER(10) NOT NULL,
STATE             VARCHAR2(10),
CONSTRAINT PRDT_PK PRIMARY KEY(PRODUCT_NO)
CONSTRAINT PRDT_SL_FK FOREIGN KEY(SELLER_NO) REFERENCE SELLER(SELLER_NO)
CONSTRAINT PRDT_CG_FK FOREIGN KEY(CATE_NO) REFERENCE PRODUCT_CATEGORY(CATE_NO) );

DROP SEQUENCE PRDT_SEQ;
CREATE SEQUENCE PRDT_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;

######## 商品還沒 INSERT 假資料 ########
INSERT INTO PRODUCT(PRODUCT_NO, SELLER_NO
######## 商品還沒 INSERT 假資料 ########

CREATE TABLE PRODUCTIMG (
IMG_NO      NUMBER(10) NOT NULL,
PRODUCT_NO  VARCHAR2(10) NOT NULL,
IMG         BLOB,
CONSTRAINT PDIMG_PK PRIMARY KEY(IMG_NO)
CONSTRAINT PDIMG_PD_FK FOREIGN KEY(PRODUCT_NO) REFENENCE PRODUCT(PRODUCT_NO) );

DROP SEQUENCE PDIMG_SEQ;
CREATE SEQUENCE PDIMG_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;





