MEMBER = 會員
REALESTATE = 房仲公司
REALTOR = 房仲
SELLER = 廠商
PRD_CATEGORY = 商品類別
PRODUCT = 商品
PRDIMG = 商品照片
PRD_COLLECTION = 收藏商品
ReportProduct = 檢舉商品案件
ReportRealtor = 檢舉房仲案件

===========有參照別人的要先DROP============================

DROP TABLE REALESTATE;
DROP TABLE REALTOR;
DROP TABLE PRDIMG;
DROP TABLE PRD_COLLECTION;
DROP TABLE REPORTPRODUCT;
DROP TABLE REPORTREALTOR;
DROP TABLE MEMBER;
DROP TABLE SELLER;
DROP TABLE PRODUCT;
DROP TABLE PRD_CATEGORY;


===== 會員 =====
CREATE TABLE MEMBER (
MEM_NO         VARCHAR2(10) NOT NULL,
MEM_MOBILE     VARCHAR2(10),
MEM_ID         VARCHAR2(40) NOT NULL,
MEM_PSW        VARCHAR2(40) NOT NULL,
MEM_NAME       VARCHAR2(12),
MEM_ADDR       VARCHAR2(100),
SEARCH_STATE   VARCHAR2(10),
LOCK_STATE     VARCHAR2(10),
MEM_GAME       NUMBER(10),
CONSTRAINT MEMBER_PK PRIMARY KEY(MEM_NO) );

DROP SEQUENCE MEM_SEQ;
CREATE SEQUENCE MEM_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0988123456','SteveJobs','123456','賈伯斯','新北市萬里區一條路9號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0956222777','MichaelJordan','123456','喬丹','台北市內湖區灌籃路168號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0933987654','PeterWu','123456','彼得吳','台北市大安區中大路8號','ON','ON',0);
INSERT INTO MEMBER VALUES ('MB'||(LPAD(to_char(MEM_SEQ.NEXTVAL),8,'0')),'0933987654','BillGates','123456','比爾蓋茲','桃園市中壢區中大路300號','ON','ON',0);


===== 房仲公司 =====
CREATE TABLE RealEstate (
RE_NO         VARCHAR2(10) NOT NULL,
RE_NAME       VARCHAR2(40) NOT NULL,
CONSTRAINT RE_PK PRIMARY KEY(RE_NO) );

DROP SEQUENCE RE_SEQ;
CREATE SEQUENCE RE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'信義房屋');
INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'永慶房屋');
INSERT INTO REALESTATE VALUES ('ESTATE'||(LPAD(to_char(ESTATE_SEQ.NEXTVAL),4,'0')),'東森房屋');


===== 房仲 =====
CREATE TABLE REALTOR (
RTR_NO          VARCHAR2(10) NOT NULL,
RTR_ID          VARCHAR2(40) NOT NULL,
RTR_PSW         VARCHAR2(40) NOT NULL,
RTRTRNAME         VARCHAR2(40),
RTRPHOTO        BLOB,
RTRAREA         VARCHAR2(40),
INTRO           CLOB,
ID_NO           VARCHAR2(10),
RE_NO           VARCHAR2(10),
RTRSTATE        VARCHAR2(10),
CONSTRAINT RTR_ESTATE_FK FOREIGN KEY(RE_NO) REFERENCES REALESTATE(RE_NO),
CONSTRAINT RTR_PK PRIMARY KEY(RTR_NO) );

DROP SEQUENCE RTR_SEQ;
CREATE SEQUENCE RTR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR01@GMAIL.COM', '123456', '葦小寶', '北投區', 'A108064497', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR02@GMAIL.COM', '123456', '王建民', '中正區', 'B123456789', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR03@GMAIL.COM', '123456', '林志玲', '士林區', 'X298765432', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR04@GMAIL.COM', '123456', '張三豐', '內湖區', 'D165432178', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR05@GMAIL.COM', '123456', '林大偉', '大安區', 'C132165491', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR06@GMAIL.COM', '123456', '李進財', '信義區', 'A198765432', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR07@GMAIL.COM', '123456', '趙德助', '萬華區', 'H147258369', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR08@GMAIL.COM', '123456', '張鈞甯', '中山區', 'X265432155', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR09@GMAIL.COM', '123456', '王小明', '大同區', 'A123466593', 'ESTATE0002', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR10@GMAIL.COM', '123456', '陳金鋒', '大安區', 'F136925874', 'ESTATE0003', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR11@GMAIL.COM', '123456', '連天邊', '信義區', 'H118754326', 'ESTATE0001', 'ON');
INSERT INTO REALTOR(RTR_NO, REALTOR_ID, RTR_PSW, RTRNAME, AREA, ID_NO, RE_NO, RTRSTATE)
VALUES('RT'||(LPAD(to_char(REALTOR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR12@GMAIL.COM', '123456', '楊美麗', '中正區', 'B213456789', 'ESTATE0001', 'ON');


===== 廠商 =====
CREATE TABLE SELLER (
SLR_NO           VARCHAR2(10) NOT NULL,
ComName          VARCHAR2(40),
TAXID            VARCHAR2(10),
SLR_ID           VARCHAR2(40) NOT NULL,
SLR_PSW          VARCHAR2(40) NOT NULL,
CONTACT          VARCHAR2(40),
SLRPHONE         VARCHAR2(10),
SLRSTATE         VARCHAR2(10),
SLRINTRO         CLOB,
CONSTRAINT SLR_PK PRIMARY KEY(SLR_NO) );

DROP SEQUENCE SLR_SEQ;
CREATE SEQUENCE SLR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO SELLER(SLR_NO, ComName, TAXID, SLR_ID, SLR_PSW, CONTACT, SLRPHONE, SLRSTATE)
VALUES('SL'||(LPAD(to_char(SLR_SEQ.NEXTVAL),8,'0')), '宜家家居', '84309586', 'SALES@IKEA.COM', '123456', '李協達', '84128869', 'ON');
INSERT INTO SELLER(SLR_NO, ComName, TAXID, SLR_ID, SLR_PSW, CONTACT, SLRPHONE, SLRSTATE)
VALUES('SL'||(LPAD(to_char(SLR_SEQ.NEXTVAL),8,'0')), '歐德傢俱', '70394175', 'SALES@ORDER.COM', '123456', '陳國都', '0800033988', 'ON');
INSERT INTO SELLER(SLR_NO, ComName, TAXID, SLR_ID, SLR_PSW, CONTACT, SLRPHONE, SLRSTATE)
VALUES('SL'||(LPAD(to_char(SLR_SEQ.NEXTVAL),8,'0')), '特力屋', '89390488', 'SALES@HOLA.COM.TW', '123456', '何湯雄', '87915566', 'ON');
INSERT INTO SELLER(SLR_NO, ComName, TAXID, SLR_ID, SLR_PSW, CONTACT, SLRPHONE, SLRSTATE)
VALUES('SL'||(LPAD(to_char(SLR_SEQ.NEXTVAL),8,'0')), '詩肯柚木', '89403884', 'SALES@HOLA.COM.TW', '123456', '林福勤', '03-3180555', 'ON');


===== 商品類別 =====
CREATE TABLE PRD_CATEGORY (
CATE_NO      VARCHAR2(10) NOT NULL,
CATE_NAME    VARCHAR2(100) NOT NULL,
CONSTRAINT PRDT_CATE_PK PRIMARY KEY(CATE_NO) );

DROP SEQUENCE PRDT_CATE_SEQ;
CREATE SEQUENCE PRDT_CATE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'桌子');
INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'椅子');
INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(to_char(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'櫃子');


===== 商品 =====
CREATE TABLE PRODUCT (
PRD_NO          VARCHAR2(10) NOT NULL,
SLR_NO          VARCHAR2(10) NOT NULL,
CATE_NO         VARCHAR2(10) NOT NULL,
PRD_NAME        VARCHAR2(50) NOT NULL,
DESCRIPTION     CLOB,
PRDSTOCK        BLOB,
PRDPRICE        NUMBER(10) NOT NULL,
PRDSTATE        VARCHAR2(10),
CONSTRAINT PRD_PK PRIMARY KEY(PRD_NO),
CONSTRAINT PRD_SL_FK FOREIGN KEY(SLR_NO) REFERENCES SELLER(SLR_NO),
CONSTRAINT PRD_CG_FK FOREIGN KEY(CATE_NO) REFERENCES PRD_CATEGORY(CATE_NO) );

DROP SEQUENCE PRD_SEQ;
CREATE SEQUENCE PRD_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;
################################
商品還沒 INSERT 假資料
INSERT INTO PRODUCT(PRD_NO, SLR_NO
################################


===== 商品照片 =====
CREATE TABLE PRDIMG (
IMG_NO      NUMBER(10) NOT NULL,
PRD_NO      VARCHAR2(10) NOT NULL,
PRDIMG      BLOB,
CONSTRAINT PRDIMG_PK PRIMARY KEY(IMG_NO),
CONSTRAINT PRDIMG_PD_FK FOREIGN KEY(PRD_NO) REFERENCES PRODUCT(PRD_NO) );

DROP SEQUENCE PRDIMG_SEQ;
CREATE SEQUENCE PRDIMG_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;
##############################
商品圖片尚未 INSERT 假資料
##############################


===== 商品收藏 (外來鍵 MEMBER_NO、PRODUCTION_NO 作為雙主鍵)=====
CREATE TABLE PRD_COLLECTION (
MEM_NO        VARCHAR2(10) NOT NULL,
PRD_NO        VARCHAR2(10) NOT NULL,
PCTIME        TIMESTAMP,
CONSTRAINT MEM_PRD_PK PRIMARY KEY (MEM_NO,PRD_NO),
CONSTRAINT PC_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT PC_PRD_FK FOREIGN KEY(PRD_NO) REFERENCES PRODUCT(PRD_NO) );


===== 檢舉商品案件 (要先建 EMPLOYEE 表格) =====
CREATE TABLE ReportProduct (
RP_NO          VARCHAR2(10) NOT NULL,
MEM_NO         VARCHAR2(10) NOT NULL,
PRD_NO         VARCHAR2(10) NOT NULL,
EMP_NO         VARCHAR2(10),
RPREASON       VARCHAR2(200),
RPRESULT       VARCHAR2(200),
RPSTATE        VARCHAR2(10),
RPTIME         TIMESTAMP,
CONSTRAINT RP_PK PRIMARY KEY(RP_NO),
CONSTRAINT RP_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT RP_PRDT_FK FOREIGN KEY(PRD_NO) REFERENCES PRODUCT(PRD_NO),
CONSTRAINT RP_EMP_FK FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) );

DROP SEQUENCE RP_SEQ;
CREATE SEQUENCE RP_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;
##############################
檢舉商品案件尚未 INSERT 假資料
##############################


===== 檢舉房仲案件 (要先建 EMPLOYEE 表格) =====
CREATE TABLE ReportRealtor (
RR_NO        VARCHAR2(10) NOT NULL,
MEM_NO       VARCHAR2(10) NOT NULL,
RTR_NO       VARCHAR2(10) NOT NULL,
EMP_NO       VARCHAR2(10),
RRREASON     VARCHAR2(200),
RRRESULT     VARCHAR2(200),
RRSTATE      VARCHAR2(10),
RRTIME       TIMESTAMP,
CONSTRAINT RR_PK PRIMARY KEY(RR_NO),
CONSTRAINT RR_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT RR_REALTOR_FK FOREIGN KEY(RTR_NO) REFERENCES REALTOR(RTR_NO),
CONSTRAINT RR_EMP_FK FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) );

DROP SEQUENCE RR_SEQ;
CREATE SEQUENCE RR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;
##############################
檢舉房仲案件尚未 INSERT 假資料
##############################

